from . import clinic_patient
from . import clinic_appointment
from . import clinic_doctor
from . import clinic_treatment
from . import clinic_medical_record
from . import clinic_prescription
from . import clinic_logs
from . import account_move
from . import account_move_line
from . import clinic_doctor_availability
from . import clinic_medicine